apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: zylvex-production
  labels:
    app: postgres
    app.kubernetes.io/part-of: zylvex
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
