"""update anchor user_id

Revision ID: update_anchor_user_id
Revises: 
Create Date: 2024-04-11 07:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'update_anchor_user_id'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change user_id from String to UUID
    op.alter_column('anchors', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anchors', 'user_id',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
