apiVersion: v1
kind: Service
metadata:
  name: mind-mapper-backend
  namespace: zylvex-production
  labels:
    app: mind-mapper-backend
    app.kubernetes.io/part-of: zylvex
spec:
  type: ClusterIP
  selector:
    app: mind-mapper-backend
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
