apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: zylvex-production
  labels:
    app: notifications-service
    app.kubernetes.io/part-of: zylvex
spec:
  type: ClusterIP
  selector:
    app: notifications-service
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
      name: http
