apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: zylvex-production
  labels:
    app: social-service
    app.kubernetes.io/part-of: zylvex
spec:
  type: ClusterIP
  selector:
    app: social-service
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: http
