apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: zylvex-production
  labels:
    app: web-app
    app.kubernetes.io/part-of: zylvex
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
